# Generated by Django 2.2 on 2020-09-17 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createcommunity', '0002_auto_20200917_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postlike',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
