# Generated by Django 2.2 on 2020-09-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcommunity', '0003_post_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postlike',
            new_name='like_users',
        ),
    ]
