# Generated by Django 2.2 on 2020-09-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcommunity', '0008_auto_20200918_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
