# Generated by Django 2.2 on 2020-09-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createcommunity', '0009_auto_20200918_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postsave',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='createcommunity.Post')),
            ],
            bases=('createcommunity.post',),
        ),
    ]
